

---
- name: Создать директорию для Grafana

  file:
    path: /opt/grafana
    state: directory
    mode: '0755'

- name: Скопировать docker-compose.yml

  template:
    src: docker-compose.yml.j2
    dest: /opt/grafana/docker-compose.yml
    mode: '0644'

- name: Скопировать prometheus.yml

  template:
    src: prometheus.yml.j2
    dest: /opt/grafana/prometheus.yml
    mode: '0644'

- name: Запустить Grafana и Prometheus

  community.docker.docker_compose_v2:
    project_src: /opt/grafana
    state: present

