- name: Create a PostgreSQL user
      postgresql_user:
        name: pg_admin
        password: 123456
        encrypted: yes
        db: demo_db
        priv: "*.*:ALL"
        state: present
      become: true
      become_user: postgres
